name: app_pelada_plus
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.2
  json_annotation: ^4.5.0
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  faker_dart: ^0.1.4
  flutter_lints: ^1.0.4
  json_serializable: ^6.2.0

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:

    # To add assets to your package, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
#  fonts:
#    - family: Pilat Extended
#      fonts:
#        - asset: assets/fonts/PilatExtended-Regular.ttf
#        - asset: assets/fonts/PilatExtended-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/PilatExtended-Black.ttf
#          weight: 900
#        - asset: assets/fonts/PilatExtended-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/PilatExtended-Light.ttf
#          weight: 200
#        - asset: assets/fonts/PilatExtended-DemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/PilatExtended-Heavy.ttf
#          weight: 800

