name: app_pelada_plus
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  json_annotation: ^4.5.0
  lottie: ^1.2.2
  mobx: ^2.0.7+2
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  faker_dart: ^0.1.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:

    # To add assets to your package, add an assets section, like this:
 assets:
   - assets/images/
   - assets/animations/

    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

